apiVersion: v1
kind: Service
metadata:
  name: {{ include "application.fullname" . }}
  annotations:
    prometheus.io/path: /actuator/prometheus
    prometheus.io/port: "8888"
    prometheus.io/scrape: "true"
  labels:
    {{- include "application.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "application.selectorLabels" . | nindent 4 }}
