apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "application.fullname" . }}-secret
data:
  vault.uri: {{ .Values.vault.uri | b64enc }}
  vault.role.id: {{ .Values.vault.role.id | b64enc }}
  vault.secret.id: {{ .Values.vault.secret.id | b64enc }}
