name: Destroy application

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  AWS_ROLE: 'arn:aws:iam::896918338968:role/GitHubActionsSkodaGoogleActions'
  VAULT_ADDR: ${{ secrets.VAULT_ADDR }}

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.3.0
        with:
          node-version: 20

      - name: Import secret
        id: import-secret
        uses: hashicorp/vault-action@v3
        with:
          url: ${{ env.VAULT_ADDR }}
          role: github-actions-secret
          method: jwt
          path: github-actions-secret
          secrets: |
            github-actions-secret/data/secret K8S_CONFIG | K8S_CONFIG ; 
            github-actions-secret/data/secret DOCKER_CONFIG | DOCKER_CONFIG ;
            github-actions-secret/data/secret VAULT_TOKEN | VAULT_TOKEN ;
            github-actions-secret/data/secret KUBE_ROOT_CA_CRT | KUBE_ROOT_CA_CRT ;
            github-actions-secret/data/secret KUBE_INTERNAL_HOST | KUBE_INTERNAL_HOST ;

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: eu-west-1

      - name: Configure K8S credentials
        run: |
          mkdir -p /home/runner/.kube
          echo $K8S_CONFIG | base64 -d > /home/runner/.kube/config

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: infra/prod

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        working-directory: infra/prod

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: infra/prod

      - name: Terraform Plan Destroy
        id: plan-destroy
        run: terraform plan -destroy -var image_tag=foobar -var docker_config=$DOCKER_CONFIG -var vault_uri=${{ env.VAULT_ADDR }} -var kubernetes_ca_cert=$KUBE_ROOT_CA_CRT -var kubernetes_internal_host=$KUBE_INTERNAL_HOST
        working-directory: infra/prod

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -var image_tag=foobar -var docker_config=$DOCKER_CONFIG -var vault_uri=${{ env.VAULT_ADDR }} -var kubernetes_ca_cert=$KUBE_ROOT_CA_CRT -var kubernetes_internal_host=$KUBE_INTERNAL_HOST -auto-approve
        working-directory: infra/prod
